apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: married-mole-nodejs 
  janus-idp.io/tekton: married-mole-nodejs
  backstage.io/kubernetes-id: married-mole-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: married-mole-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  