apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: married-mole-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: married-mole-nodejs 
  name: married-mole-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: married-mole-nodejs 
